===== 2025-10-03T02:00:00-05:00 â€” last 300 lines =====
2025-10-02 18:29:37.026 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:29:50.466 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:30:03.906 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:30:17.348 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:30:30.786 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:30:44.226 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:31:02.066 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:31:15.506 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:31:28.946 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:31:42.386 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:31:55.826 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:32:02.746 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 for modules 'Time, AutoOff, DeviceModule' after first update: ('Unable to query the device: 192.168.1.84: ', TimeoutError())
2025-10-02 18:32:08.746 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_time' after first update: ('Unable to query the device: 192.168.1.84: ', TimeoutError())
2025-10-02 18:32:09.266 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:32:14.746 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_auto_off_config' after first update: ('Unable to query the device: 192.168.1.84: ', TimeoutError())
2025-10-02 18:32:20.746 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_info' after first update: ('Unable to query the device: 192.168.1.84: ', TimeoutError())
2025-10-02 18:32:26.746 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_usage' after first update: ('Unable to query the device: 192.168.1.84: ', TimeoutError())
2025-10-02 18:32:26.747 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.1.84 data: Unable to communicate with the device update: get_device_info not found in {'get_device_time': <SmartErrorCode.INTERNAL_QUERY_ERROR: -100001>, 'get_auto_off_config': <SmartErrorCode.INTERNAL_QUERY_ERROR: -100001>, 'get_device_info': <SmartErrorCode.INTERNAL_QUERY_ERROR: -100001>, 'get_device_usage': <SmartErrorCode.INTERNAL_QUERY_ERROR: -100001>} for device 192.168.1.84
2025-10-02 18:32:27.026 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:32:37.746 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ('Unable to query the device: 192.168.1.84: ', TimeoutError())
2025-10-02 18:32:40.466 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:32:43.747 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_time' after first update: ('Unable to query the device: 192.168.1.84: ', TimeoutError())
2025-10-02 18:32:53.906 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:32:54.066 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:33:07.346 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:33:07.506 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:33:20.786 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:33:20.946 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:33:34.226 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:33:34.386 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:33:52.066 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:33:52.306 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:34:05.506 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:34:05.746 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:34:18.946 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:34:19.186 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:34:32.386 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:34:32.626 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:34:45.826 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:34:46.066 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:34:59.266 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:34:59.506 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:35:17.026 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:35:17.346 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:35:30.466 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:35:30.786 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:35:43.906 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:35:44.226 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:35:57.346 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:35:57.666 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:36:10.786 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:36:11.106 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:36:24.226 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:36:24.546 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:36:42.066 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:36:42.306 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:36:55.506 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:36:55.746 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:37:08.946 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:37:09.186 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:37:22.386 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:37:22.626 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:37:35.826 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:37:36.066 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:37:49.266 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:37:49.506 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:38:07.026 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:38:07.346 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:38:20.466 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:38:20.786 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:38:33.906 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:38:34.226 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:38:47.346 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:38:47.666 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:39:00.786 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:39:01.106 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:39:14.226 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:39:14.546 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:39:32.066 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:39:32.306 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:39:45.506 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:39:45.746 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:39:58.946 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:39:59.186 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:40:12.386 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:40:12.626 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:40:25.826 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:40:26.066 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:40:39.266 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:40:39.506 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:40:57.026 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:40:57.346 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:41:10.466 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:41:10.786 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:41:23.906 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:41:24.226 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:41:37.346 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:41:37.666 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:41:50.786 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:41:51.106 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:42:04.226 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:42:04.546 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:42:22.066 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:42:22.306 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:42:35.506 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:42:35.746 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:42:48.946 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:42:49.186 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:43:02.386 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:43:02.626 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:43:15.826 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:43:16.066 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:43:29.266 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:43:29.506 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:43:47.026 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:43:47.346 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:44:00.466 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:44:00.786 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:44:13.906 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:44:14.226 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:44:27.346 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:44:27.666 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:44:40.786 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:44:41.106 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:44:54.226 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:44:54.546 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:45:12.066 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:45:12.306 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:45:25.506 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:45:25.746 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:45:38.946 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:45:39.186 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:45:52.386 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:45:52.626 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:46:05.826 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:46:06.066 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:46:19.266 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:46:19.506 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:46:37.026 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:46:37.346 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:46:50.466 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:46:50.786 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:47:03.906 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:47:04.226 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:47:17.346 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:47:17.666 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:47:30.786 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:47:31.106 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:47:44.226 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:47:44.546 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:48:02.066 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:48:02.306 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:48:15.506 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:48:15.746 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:48:28.946 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:48:29.186 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:48:42.386 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:48:42.626 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:48:55.826 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:48:56.066 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:49:09.266 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:49:09.506 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:49:27.026 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:49:27.346 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:49:40.466 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:49:40.786 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:49:53.906 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:49:54.226 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:50:07.346 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:50:07.666 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:50:20.786 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:50:21.106 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:50:34.226 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:50:34.546 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:50:52.066 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:50:52.306 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:51:05.506 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:51:05.746 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:51:18.946 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:51:19.186 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:51:32.386 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:51:32.626 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:51:45.826 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:51:46.066 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:51:59.266 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:51:59.506 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:52:17.026 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:52:17.346 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:52:30.466 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:52:30.786 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:52:43.906 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:52:44.226 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:52:57.426 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:52:57.666 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:53:10.866 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:53:11.106 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:53:24.306 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:53:24.546 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:53:42.066 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:53:42.306 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:53:55.506 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:53:55.746 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:54:08.946 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:54:09.186 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:54:22.386 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:54:22.626 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:54:35.826 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:54:36.066 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:54:49.266 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:54:49.506 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:55:07.026 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:55:07.346 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:55:20.466 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:55:20.786 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:55:33.906 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:55:34.226 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:55:47.346 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:55:47.666 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:56:00.786 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:56:01.106 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:56:14.226 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:56:14.546 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:56:32.066 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:56:32.306 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:56:45.506 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:56:45.746 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:56:58.946 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:56:59.186 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:57:12.386 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:57:12.626 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_connect_cloud_state' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:57:25.826 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:57:26.066 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_info' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:57:39.266 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:57:39.506 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_usage' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:57:57.026 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:57:57.346 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 for modules 'Time, AutoOff, Cloud, DeviceModule' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:58:10.466 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:58:10.786 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_device_time' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 18:58:23.906 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.81 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.81: Cannot connect to host 192.168.1.81:80 ssl:<ssl.SSLContext object at 0xffff657a42d0> [Connect call failed ('192.168.1.81', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.81', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a42d0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.81', 80)")))
2025-10-02 18:58:24.226 ERROR (MainThread) [kasa.smart.smartdevice] Error querying 192.168.1.84 individually for module query 'get_auto_off_config' after first update: ("Device connection error: 192.168.1.84: Cannot connect to host 192.168.1.84:80 ssl:<ssl.SSLContext object at 0xffff657a4370> [Connect call failed ('192.168.1.84', 80)]", ClientConnectorError(ConnectionKey(host='192.168.1.84', port=80, is_ssl=False, ssl=<ssl.SSLContext object at 0xffff657a4370>, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed ('192.168.1.84', 80)")))
2025-10-02 19:00:59.545 WARNING (Recorder) [homeassistant.components.recorder.entity_registry] Cannot migrate history for entity_id `binary_sensor.main_lights_tapo_cloud_connection` to `binary_sensor.main_lights_cloud_connection` because the new entity_id is already in use
2025-10-02 19:00:59.841 WARNING (Recorder) [homeassistant.components.recorder.entity_registry] Cannot migrate history for entity_id `switch.main_lights_tapo` to `switch.main_lights` because the new entity_id is already in use
2025-10-02 19:00:59.923 WARNING (Recorder) [homeassistant.components.recorder.entity_registry] Cannot migrate history for entity_id `switch.main_lights_tapo_led` to `switch.main_lights_led` because the new entity_id is already in use
2025-10-02 19:08:08.465 ERROR (MainThread) [homeassistant.components.automation.bedroom_ceiling_lights_3_set_my_room] Bedroom Ceiling Lights (3) -> Set My Room: If at step 3: Choose at step 1: choice 1: Error executing script. Error for call_service at pos 1: Invalid response from Roku API
2025-10-02 19:08:08.466 ERROR (MainThread) [homeassistant.components.automation.bedroom_ceiling_lights_3_set_my_room] Bedroom Ceiling Lights (3) -> Set My Room: If at step 3: Error executing script. Error for choose at pos 1: Invalid response from Roku API
2025-10-02 19:08:08.467 ERROR (MainThread) [homeassistant.components.automation.bedroom_ceiling_lights_3_set_my_room] Bedroom Ceiling Lights (3) -> Set My Room: Error executing script. Error for if at pos 3: Invalid response from Roku API
2025-10-02 19:08:08.471 ERROR (MainThread) [homeassistant.components.automation.bedroom_ceiling_lights_3_set_my_room] Error while executing automation automation.bedroom_ceiling_lights_3_set_my_room: Invalid response from Roku API
2025-10-02 19:21:01.415 ERROR (MainThread) [homeassistant.components.automation] Failed to generate automation from blueprint: Missing input source_entity
2025-10-02 19:21:01.419 ERROR (MainThread) [homeassistant.components.automation] Failed to generate automation from blueprint: Missing input source_entity
2025-10-02 20:04:49.879 ERROR (MainThread) [homeassistant.components.roku.coordinator] Error fetching roku data: Invalid response from API: Timeout occurred while connecting to device
2025-10-02 21:57:27.336 ERROR (MainThread) [homeassistant.components.matter] Failed to get Matter Server add-on discovery info
2025-10-02 21:57:32.342 ERROR (MainThread) [homeassistant.components.matter] Failed to get Matter Server add-on discovery info
2025-10-02 22:41:40.775 ERROR (MainThread) [frontend.js.modern.202509035] Uncaught error from WebKit 605.1.15 on iOS 18.7
TypeError: e is not an Object. (evaluating '"trigger"in e')
AutomationConfig,> (src/data/automation.ts:398:19)
saveAutomationConfig (src/data/automation.ts:379:35)
ev.stopPropagation (src/panels/config/automation/ha-automation-editor.ts:803:35)
this (src/lit-html.ts:2109:33)
dispatchEvent ([native code]::)
event (src/common/dom/fire_event.ts:75:21)
this.hass.localize (src/components/ha-yaml-editor.ts:173:14)
this (src/lit-html.ts:2109:33)
dispatchEvent ([native code]::)
event (src/common/dom/fire_event.ts:75:21)
2025-10-02 22:48:06.060 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities scene.evening are missing or not currently available
2025-10-02 23:00:28.879 ERROR (MainThread) [homeassistant.components.roku.coordinator] Error fetching roku data: Invalid response from API: Timeout occurred while connecting to device
2025-10-02 23:32:17.693 ERROR (MainThread) [homeassistant.components.device_automation] Unexpected error fetching device triggers
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hue/device_trigger.py", line 107, in async_get_triggers
    return async_get_triggers_v2(bridge, device_entry)
  File "/usr/src/homeassistant/homeassistant/components/hue/v2/device_trigger.py", line 94, in async_get_triggers
    model_id = api.devices[hue_dev_id].product_data.product_name
               ~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohue/v2/controllers/base.py", line 180, in __getitem__
    return self._items[id]
           ~~~~~~~~~~~^^^^
KeyError: '89c65702-a2b1-4451-a88f-7b946c6a609d'
2025-10-02 23:35:04.233 ERROR (MainThread) [homeassistant.components.device_automation] Unexpected error fetching device triggers
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hue/device_trigger.py", line 107, in async_get_triggers
    return async_get_triggers_v2(bridge, device_entry)
  File "/usr/src/homeassistant/homeassistant/components/hue/v2/device_trigger.py", line 94, in async_get_triggers
    model_id = api.devices[hue_dev_id].product_data.product_name
               ~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohue/v2/controllers/base.py", line 180, in __getitem__
    return self._items[id]
           ~~~~~~~~~~~^^^^
KeyError: '89c65702-a2b1-4451-a88f-7b946c6a609d'
2025-10-02 23:39:50.809 ERROR (MainThread) [homeassistant.components.device_automation] Unexpected error fetching device triggers
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hue/device_trigger.py", line 107, in async_get_triggers
    return async_get_triggers_v2(bridge, device_entry)
  File "/usr/src/homeassistant/homeassistant/components/hue/v2/device_trigger.py", line 94, in async_get_triggers
    model_id = api.devices[hue_dev_id].product_data.product_name
               ~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohue/v2/controllers/base.py", line 180, in __getitem__
    return self._items[id]
           ~~~~~~~~~~~^^^^
KeyError: '89c65702-a2b1-4451-a88f-7b946c6a609d'
2025-10-03 00:19:49.879 ERROR (MainThread) [homeassistant.components.roku.coordinator] Error fetching roku data: Invalid response from API: Timeout occurred while connecting to device
